# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [1]:
import numpy as np

In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [10]:
array = np.full((2,3),1) #creating 2x3 numpy array with a value of 1
a = array[0]
b = array[1]
a + b # one single array with the sum of 1+1

array([2, 2, 2])

Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [29]:
c = np.full((3,2),1)
c
# a + c yapamazsin cünkü farkli sütun sayilari var

array([[1, 1],
       [1, 1],
       [1, 1]])

Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [17]:
d = np.transpose(c)
a + d

array([[2, 2, 2],
       [2, 2, 2]])

Which combination of arrays are you able to multiply with each other? Why?

In [31]:
#number of columns must be equal

Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [42]:
lst = []
for x in range(0,10):
    lst.append(x)
print(lst)
print("===============================")
print(np.square(lst))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0  1  4  9 16 25 36 49 64 81]


Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [55]:
# your code here
np_array = np.random.randint(100,size=(100,100))
print(np_array)

[[29 20 37 ... 37 61 34]
 [28 26 72 ... 96 51 74]
 [54 51 72 ...  2  4 82]
 ...
 [67 49 74 ... 40 47 87]
 [95 25 91 ... 39 92 26]
 [31 78 50 ... 78 39  8]]


In [57]:
np.fill_diagonal(np_array, range(0,100))
print(np_array)

[[ 0 20 37 ... 37 61 34]
 [28  1 72 ... 96 51 74]
 [54 51  2 ...  2  4 82]
 ...
 [67 49 74 ... 97 47 87]
 [95 25 91 ... 39 98 26]
 [31 78 50 ... 78 39 99]]
